[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NEXT_PUBLIC_SUPABASE_URL = "https://iufkgqtastuwlequwwlw.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "sb_publishable_1ES8INP2q5YHI4uJWIIYlw_zmq8_TzL"

[[plugins]]
  package = "@netlify/plugin-nextjs"
